name: Run Advisor

permissions:
  issues: write
  contents: write

on:
  workflow_dispatch:

jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v5
    - name: Run Advisor on Initial
      uses: jzheaux/spring-guides-actions/run-advisor@main
      with:
        spring-enterprise-username: ${{ secrets.SPRING_ENTERPRISE_USERNAME }}
        spring-enterprise-token: ${{ secrets.SPRING_ENTERPRISE_TOKEN }}
        directory: initial
    - name: Run Advisor on Complete
      uses: jzheaux/spring-guides-actions/run-advisor@main
      with:
        spring-enterprise-username: ${{ secrets.SPRING_ENTERPRISE_USERNAME }}
        spring-enterprise-token: ${{ secrets.SPRING_ENTERPRISE_TOKEN }}
        directory: complete

